# Generated by rk. Edits are overwritten and will make the
# next release stop, because rk compares this file to the
# release it names.
cask "rk" do
  version "0.1.0"

  on_macos do
    sha256 "5cd3bb088b7c655d7a3e62a4bf363e3cc4dc869f01bd2e4eb8d8e611ca731bcd"
    url "https://github.com/danReynolds/release-kit/releases/download/v0.1.0/rk-0.1.0-macos-arm64.tar.gz"

    depends_on arch: :arm64
  end

  on_linux do
    arch arm: "arm64", intel: "x64"

    sha256 arm64_linux:  "ff5e16dafcfb7a0301559637b42e262c35d9e1c19e3aadbc7852e9df420d308f",
           x86_64_linux: "875893bad8e5ca9303b3d35ee39904144b49d04c2f812eefc12ccc0ea9adb476"

    url "https://github.com/danReynolds/release-kit/releases/download/v0.1.0/rk-#{version}-linux-#{arch}.tar.gz"
  end

  name "rk"
  desc "Released by rk"
  homepage "https://github.com/danReynolds/release-kit"

  binary "rk"
end
