# Generated by rk. Edits are overwritten and will make the
# next release stop, because rk compares this file to the
# release it names.
cask "rk" do
  version "0.1.5"

  on_macos do
    sha256 "daa865da431a17b96de35e941c348d46fff19cb79ffe4feae952ccd3b31169ae"
    url "https://github.com/danReynolds/release-kit/releases/download/v0.1.5/rk-0.1.5-macos-arm64.tar.gz"

    depends_on arch: :arm64
  end

  on_linux do
    arch arm: "arm64", intel: "x64"

    sha256 arm64_linux:  "6552601a55b4ab971e788a9593b51f9ae25d71a6e5c8cbe644478e8a3996bda0",
           x86_64_linux: "3eef82abbc6bb3f6042da0a8c89cbfa378668144e64205b22f6701e7c91d4fca"

    url "https://github.com/danReynolds/release-kit/releases/download/v0.1.5/rk-#{version}-linux-#{arch}.tar.gz"
  end

  name "rk"
  desc "Released by rk"
  homepage "https://github.com/danReynolds/release-kit"

  binary "rk"
end
