# Generated by rk. Edits are overwritten and will make the
# next release stop, because rk compares this file to the
# release it names.
cask "rk" do
  version "0.1.6"

  on_macos do
    sha256 "cbbca9abfadab92d07060d7689590244b8e39a3fe3c2b1b81a0f23357b60a878"
    url "https://github.com/danReynolds/release-kit/releases/download/v0.1.6/rk-0.1.6-macos-arm64.tar.gz"

    depends_on arch: :arm64
  end

  on_linux do
    arch arm: "arm64", intel: "x64"

    sha256 arm64_linux:  "642847851109ec10064ef3d3474de7c3cc32b43d8190218e5673acbe4490a689",
           x86_64_linux: "c8246174d19e382bee9aaabaf349dc6a46a58bfe69b669b8e7efb6922514f4f4"

    url "https://github.com/danReynolds/release-kit/releases/download/v0.1.6/rk-#{version}-linux-#{arch}.tar.gz"
  end

  name "rk"
  desc "Released by rk"
  homepage "https://github.com/danReynolds/release-kit"

  binary "rk"
end
