# typed: strict
# frozen_string_literal: true

# Generated by rk. Edits are overwritten and will make the
# next release stop, because rk compares this file to the
# release it names.
class Keybay < Formula
  desc "Released by rk"
  homepage "https://github.com/danReynolds/keybay"
  version "0.1.1"

  on_macos do
    on_arm do
      url "https://github.com/danReynolds/keybay/releases/download/keybay_cli-v0.1.1/keybay-0.1.1-macos-arm64.tar.gz"
      sha256 "fd853c64210f62b4c44eba4a0f33e90407dc999a046808857e073a91aa5de2c0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/danReynolds/keybay/releases/download/keybay_cli-v0.1.1/keybay-0.1.1-linux-arm64.tar.gz"
      sha256 "a2f5de819b373dc18a7a323ef3dfa35b78f935a608beb2d9bf725a2ffc6bac9c"
    end
    on_intel do
      url "https://github.com/danReynolds/keybay/releases/download/keybay_cli-v0.1.1/keybay-0.1.1-linux-x64.tar.gz"
      sha256 "17da1a843141e7bc19b5585e289974b79b8b7e8a0457e6d6888d97440ca9924f"
    end
  end

  def install
    bin.install "keybay"
  end

  test do
    assert_match version.to_s,
                 shell_output("#{bin}/keybay --version")
  end
end
