# typed: strict
# frozen_string_literal: true

# Generated by rk. Edits are overwritten and will make the
# next release stop, because rk compares this file to the
# release it names.
class Rk < Formula
  desc "Released by rk"
  homepage "https://github.com/danReynolds/release-kit"
  version "0.1.10"

  on_macos do
    on_arm do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.10/rk-0.1.10-macos-arm64.tar.gz"
      sha256 "71fe860212d65805d32d24e69218de33cb02e8d75543863058b1c276ed3955c7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.10/rk-0.1.10-linux-arm64.tar.gz"
      sha256 "2042858f8e3caa48f8a3b151a353c1a9a232d1f52bc9637cb33c946fc29eef9d"
    end
    on_intel do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.10/rk-0.1.10-linux-x64.tar.gz"
      sha256 "105b5c2066627565d173aa3f94ef6501a550e3762b557f64468f672819533023"
    end
  end

  def install
    bin.install "rk"
  end

  test do
    assert_match version.to_s,
                 shell_output("#{bin}/rk --version")
  end
end
