# typed: strict
# frozen_string_literal: true

# Generated by rk. Edits are overwritten and will make the
# next release stop, because rk compares this file to the
# release it names.
class Rk < Formula
  desc "Released by rk"
  homepage "https://github.com/danReynolds/release-kit"
  version "0.1.12"

  on_macos do
    on_arm do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.12/rk-0.1.12-macos-arm64.tar.gz"
      sha256 "cbef44a8aa29016ac2de5a5da1b15f7faa265f21054dc5ad91735c6ebbda39d7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.12/rk-0.1.12-linux-arm64.tar.gz"
      sha256 "49a2f42d04c17da0716261ca3cd2d26f0054b98fddf4ffdde2398993563803cb"
    end
    on_intel do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.12/rk-0.1.12-linux-x64.tar.gz"
      sha256 "3950b28ccc3c83cac9007c922b75708082288190d92f6b3f8233fee5aedbedf1"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"rk"
  end

  test do
    assert_match version.to_s,
                 shell_output("#{bin}/rk --version")
  end
end
