# typed: strict
# frozen_string_literal: true

# Generated by rk. Edits are overwritten and will make the
# next release stop, because rk compares this file to the
# release it names.
class Rk < Formula
  desc "Released by rk"
  homepage "https://github.com/danReynolds/release-kit"
  version "0.1.11"

  on_macos do
    on_arm do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.11/rk-0.1.11-macos-arm64.tar.gz"
      sha256 "00780f8606f18d57c041539a8f4aa7f21653a9fdc9da34a47a3f411f2c93382e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.11/rk-0.1.11-linux-arm64.tar.gz"
      sha256 "2da5afe68b83618c1a99dbfcd58a00da6272a0b5cb5cc9610449f31a062c0b48"
    end
    on_intel do
      url "https://github.com/danReynolds/release-kit/releases/download/v0.1.11/rk-0.1.11-linux-x64.tar.gz"
      sha256 "285700f5336fbd4e70d36b0da489941617baefa22907f9140a5fbe48658370a3"
    end
  end

  def install
    bin.install "rk"
  end

  test do
    assert_match version.to_s,
                 shell_output("#{bin}/rk --version")
  end
end
